# Generated by Django 5.0.6 on 2024-07-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_star', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
